In [1]:
import pandas as pd
import plotly.express as px
from statsmodels.tsa.seasonal import seasonal_decompose
import logging
import datetime
import time

from datetime import datetime

from pyspark.sql.functions import col, datediff
import dash
from dash import dcc, html
from dash.dependencies import Input, Output

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, substring, year, current_date, when

import calendar
import pandas as pd
import plotly.express as px
from pyspark.sql import SparkSession
from pyspark.sql.functions import concat, col
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.seasonal import seasonal_decompose
from ipywidgets import interact, widgets
from matplotlib.dates import MonthLocator, DateFormatter
import geopandas as gpd
from shapely.geometry import Point
from sklearn.preprocessing import StandardScaler
from statsmodels.tsa.holtwinters import ExponentialSmoothing
import geopandas as gpd
from mpl_toolkits.axes_grid1 import make_axes_locatable
#from fbprophet import Prophet
from sklearn.metrics import mean_squared_error
import numpy as np
import plotly.graph_objects as go
from pyspark.sql import functions as F
from pyspark.sql.functions import year, month
from sklearn.metrics.pairwise import euclidean_distances
from pyspark.sql.functions import year, month, sum as sum_
from scipy.spatial.distance import euclidean
from prophet import Prophet
from pyspark.sql.functions import col, countDistinct , desc , count , length
from pyspark.sql.functions import split, col, when
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, udf, dayofmonth, last_day ,to_date, lit, isnull
from pyspark.sql.types import IntegerType
import numpy as np
from sklearn.metrics import r2_score, mean_squared_error
from dateutil.relativedelta import relativedelta
from pyspark.sql.functions import date_format

from pyspark.sql.functions import col, coalesce, current_date, months_between, round
from pyspark.sql.functions import regexp_replace

import schedule
from pyspark.sql.functions import col, to_timestamp, date_format

import pyspark
import pandas as pd
import boto3
import sagemaker
import sagemaker.feature_store.feature_store as fs
import databricks.connect
from dateutil.relativedelta import relativedelta

import pandas as pd
import numpy as np
import plotly.graph_objects as go
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error, mean_absolute_error
from sklearn.metrics import mean_squared_error, root_mean_squared_error

import pandas as pd
import numpy as np
from prophet import Prophet
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error
import plotly.graph_objects as go
from itertools import product
import random
import statsmodels.api as sm
import os

from pyspark.sql import functions as F
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, months_between, current_date,expr
from pyspark.sql.functions import col, substr

import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
from databricks.connect import DatabricksSession


# Get spark
spark = databricks.connect.DatabricksSession.builder.getOrCreate()

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\pydantic\_internal\_fields.py:192: UserWarning: Field name "json" in "MonitoringDatasetFormat" shadows an attribute in parent "Base"
  warnings.warn(

[02/19/25 19:09:08] INFO     Found credentials in shared credentials file: ~/.aws/credentials   ]8;id=934146;file://c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\botocore\credentials.py\credentials.py]8;;\:]8;id=877074;file://c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\botocore\credentials.py#1278\1278]8;;\

sagemaker.config INFO - Not applying SDK defaults from location: C:\ProgramData\sagemaker\sagemaker\config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: C:\Users\gusta\AppData\Local\sagemaker\sagemaker\config.yaml

In [5]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [60]:
# Substitua 'arquivo.xlsx' pelo caminho do seu arquivo Excel
tabela_nova_df = pd.read_csv(r"C:\Users\gusta\OneDrive\Área de Trabalho\survivor\tabela_sobrevivencia_2.csv")

tabela_nova_df["data_primeiro_boleto"] = pd.to_datetime(tabela_nova_df["data_primeiro_boleto"], errors='coerce')
# Arredondando para duas casas decimais
tabela_nova_df['boletos_gerados_anos'] = tabela_nova_df['boletos_gerados_anos'].round(2)

tabela_nova_df["ano_primeiro_boleto"] = tabela_nova_df["data_primeiro_boleto"].dt.year

# Exibir as primeiras linhas do DataFrame
display(tabela_nova_df.head(5))

,contratos,documento,cliente,data_inicio,data_final,max_conexao,data_primeiro_boleto,data_ultimo_boleto,boletos_gerados,total_valor_pago,tipo_saida,meses_contrato,meses_boleto,anos_boleto,anos_contrato,churn,ano_inicio,diferenca_meses_inicio_primeiro_boleto,diferenca_meses_final_ultimo_boleto,classifica_diferenca_boleto_tempo_inicial,classifica_diferenca_boleto_tempo_final,boletos_gerados_anos,CNPJ_CPF,CNAE_RF,Hierarquia,uf,data_inicio_atividade,ano_inicio_atividade,idade,ano_primeiro_boleto
0,1,750329882,457047,2010-11-30,2018-05-02,0.0,2017-10-01,2018-05-01,8,452.6,90 DIAS BLOQUEADO,89.0,7.00,0.58,7.42,1,2010,83,0,Maior que 24 meses,0 a 1 mês,0.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
1,1,17880000109,194574,2007-04-23,2009-08-31,-1.0,2007-05-01,2009-09-01,28,1541.6,CANCELAMENTO NORMAL,28.0,28.00,2.33,2.33,1,2007,1,1,0 a 1 mês,0 a 1 mês,2.33,1.788000e+10,4744005.0,Comércio; Comércio varejista; Materiais de con...,SP,19940614.0,1994.0,31.0,2007
2,1,30277000167,224704,2009-02-06,2010-06-05,-3.0,2009-03-01,2012-12-06,14,207.5,OUTROS,16.0,45.16,3.76,1.33,1,2009,1,31,0 a 1 mês,Maior que 24 meses,1.17,3.027700e+10,1013902.0,Indústria; Indústrias de Transformação; Alimen...,SP,19940824.0,1994.0,31.0,2009
3,1,78792000117,224933,2009-01-23,2010-01-14,-1.0,2009-02-01,2012-12-06,9,141.7,CANCELAMENTO NORMAL,12.0,46.16,3.85,1.00,1,2009,1,35,0 a 1 mês,Maior que 24 meses,0.75,7.879200e+10,4921301.0,Serviços; Transporte; Transporte terrestre,PR,19940530.0,1994.0,31.0,2009
4,1,102401000152,27915,2002-03-18,2008-03-31,-1.0,2006-02-01,2008-05-01,15,353.4,CANCELAMENTO NORMAL,72.0,27.00,2.25,6.00,1,2002,47,2,Maior que 24 meses,2 a 5 meses,1.25,1.024010e+11,4731800.0,Comércio; Comércio varejista; Combustíveis,GO,19940630.0,1994.0,31.0,2006

In [58]:
# Garantir que as colunas estão no formato datetime
tabela_nova_df["data_inicio"] = pd.to_datetime(tabela_nova_df["data_inicio"], errors="coerce")
tabela_nova_df["data_primeiro_boleto"] = pd.to_datetime(tabela_nova_df["data_primeiro_boleto"], errors="coerce")

In [7]:
total_linhas = len(tabela_nova_df)
print(f"Total de linhas: {total_linhas}")

Total de linhas: 130225

In [8]:
print(tabela_nova_df.dtypes)

contratos                                      int64
documento                                      int64
cliente                                        int64
data_inicio                                   object
data_final                                    object
max_conexao                                  float64
data_primeiro_boleto                          object
data_ultimo_boleto                            object
boletos_gerados                                int64
total_valor_pago                             float64
tipo_saida                                    object
meses_contrato                               float64
meses_boleto                                 float64
anos_boleto                                  float64
anos_contrato                                float64
churn                                          int64
ano_inicio                                     int64
diferenca_meses_inicio_primeiro_boleto         int64
diferenca_meses_final_ultimo_boleto            int64
classifica_diferenca_boleto_tempo_inicial     object
classifica_diferenca_boleto_tempo_final       object
boletos_gerados_anos                         float64
CNPJ_CPF                                     float64
CNAE_RF                                      float64
Hierarquia                                    object
uf                                            object
data_inicio_atividade                        float64
ano_inicio_atividade                         float64
idade                                        float64
dtype: object

In [9]:
print(tabela_nova_df.isnull().sum())

contratos                                        0
documento                                        0
cliente                                          0
data_inicio                                      0
data_final                                   13485
max_conexao                                  13485
data_primeiro_boleto                             0
data_ultimo_boleto                           13485
boletos_gerados                                  0
total_valor_pago                                 0
tipo_saida                                       0
meses_contrato                                   0
meses_boleto                                     0
anos_boleto                                      0
anos_contrato                                    0
churn                                            0
ano_inicio                                       0
diferenca_meses_inicio_primeiro_boleto           0
diferenca_meses_final_ultimo_boleto              0
classifica_diferenca_boleto_tempo_inicial        0
classifica_diferenca_boleto_tempo_final          0
boletos_gerados_anos                             0
CNPJ_CPF                                       222
CNAE_RF                                        239
Hierarquia                                     239
uf                                             222
data_inicio_atividade                          222
ano_inicio_atividade                           222
idade                                          222
dtype: int64

In [10]:
import pandas as pd

# Contar quantidade de valores iguais a zero
quantidade_zero = (tabela_nova_df['anos_contrato'] == 0).sum()

# Contar quantidade de valores negativos
quantidade_negativos = (tabela_nova_df['anos_contrato'] < 0).sum()

print(f"Quantidade de anos_boleto iguais a zero: {quantidade_zero}")
print(f"Quantidade de anos_boleto negativos: {quantidade_negativos}")

Quantidade de anos_boleto iguais a zero: 0
Quantidade de anos_boleto negativos: 0

In [11]:
import pandas as pd

# Contar quantidade de valores iguais a zero
quantidade_zero = (tabela_nova_df['anos_boleto'] == 0).sum()

# Contar quantidade de valores negativos
quantidade_negativos = (tabela_nova_df['anos_boleto'] < 0).sum()

print(f"Quantidade de anos_boleto iguais a zero: {quantidade_zero}")
print(f"Quantidade de anos_boleto negativos: {quantidade_negativos}")

Quantidade de anos_boleto iguais a zero: 5862
Quantidade de anos_boleto negativos: 0

In [12]:
import pandas as pd

# Contar quantidade de valores iguais a zero
quantidade_zero = (tabela_nova_df['boletos_gerados_anos'] == 0).sum()

# Contar quantidade de valores negativos
quantidade_negativos = (tabela_nova_df['boletos_gerados_anos'] < 0).sum()

print(f"Quantidade de boletos_gerados_anos iguais a zero: {quantidade_zero}")
print(f"Quantidade de boletos_gerados_anos negativos: {quantidade_negativos}")

Quantidade de boletos_gerados_anos iguais a zero: 0
Quantidade de boletos_gerados_anos negativos: 0

tabela_nova_df_2006 =

In [61]:
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime

def analisar_permanencia_comparada(tabela_df):
    """
    Analisa e compara o tempo de permanência dos contratos baseados na data de início e na data do primeiro boleto.

    Parâmetros:
    tabela_df (pd.DataFrame): DataFrame contendo 'data_inicio', 'anos_contrato', 
                              'data_primeiro_boleto', 'anos_boleto' e 'tipo_saida'.
    
    Retorno:
    fig (plotly.graph_objects.Figure): Gráfico interativo comparando os tempos de permanência.
    """
    # Filtrar apenas contratos cancelados (excluir "ATIVO")
    df_contratos = tabela_df[tabela_df["tipo_saida"] != "ATIVO"].copy()

    df_contratos = tabela_nova_df[
    (tabela_nova_df["ano_inicio"] >= 2006) & 
    (tabela_nova_df["ano_primeiro_boleto"] >= 2006)]
    
    # Converter colunas de data para datetime
    df_contratos["data_inicio"] = pd.to_datetime(df_contratos["data_inicio"], errors='coerce')
    df_contratos["data_primeiro_boleto"] = pd.to_datetime(df_contratos["data_primeiro_boleto"], errors='coerce')
    
    # Criar colunas com o ano do contrato e o ano do primeiro boleto
    df_contratos["ano_inicio"] = df_contratos["data_inicio"].dt.year
    df_contratos["ano_primeiro_boleto"] = df_contratos["data_primeiro_boleto"].dt.year
    

    
    # Obter o ano atual
    ano_atual = datetime.today().year
    
    # Calcular estatísticas por ano para os contratos
    estatisticas_contratos = df_contratos.groupby("ano_inicio")["anos_contrato"].agg(["median", "mean"]).reset_index()
    estatisticas_contratos["tempo_maximo_possivel"] = ano_atual - estatisticas_contratos["ano_inicio"]
    
    # Calcular estatísticas por ano para os boletos
    estatisticas_boletos = df_contratos.groupby("ano_primeiro_boleto")["boletos_gerados_anos"].agg(["median", "mean"]).reset_index()
    estatisticas_boletos["tempo_maximo_possivel"] = ano_atual - estatisticas_boletos["ano_primeiro_boleto"]
    
    # Criar gráfico interativo
    fig = go.Figure()
    
    # Adicionar linhas dos contratos
    fig.add_trace(go.Scatter(
        x=estatisticas_contratos["ano_inicio"],
        y=estatisticas_contratos["median"],
        mode="lines+markers",
        name="Mediana Contratos",
        line=dict(color="blue")
    ))
    
    fig.add_trace(go.Scatter(
        x=estatisticas_contratos["ano_inicio"],
        y=estatisticas_contratos["mean"],
        mode="lines+markers",
        name="Média Contratos",
        line=dict(color="green")
    ))
    
    fig.add_trace(go.Scatter(
        x=estatisticas_contratos["ano_inicio"],
        y=estatisticas_contratos["tempo_maximo_possivel"],
        mode="lines",
        name="Tempo Máximo Contratos",
        line=dict(color="red", dash="dash")
    ))
    
    # Adicionar linhas dos boletos
    fig.add_trace(go.Scatter(
        x=estatisticas_boletos["ano_primeiro_boleto"],
        y=estatisticas_boletos["median"],
        mode="lines+markers",
        name="Mediana Boletos",
        line=dict(color="purple")
    ))
    
    fig.add_trace(go.Scatter(
        x=estatisticas_boletos["ano_primeiro_boleto"],
        y=estatisticas_boletos["mean"],
        mode="lines+markers",
        name="Média Boletos",
        line=dict(color="orange")
    ))
    
    fig.add_trace(go.Scatter(
        x=estatisticas_boletos["ano_primeiro_boleto"],
        y=estatisticas_boletos["tempo_maximo_possivel"],
        mode="lines",
        name="Tempo Máximo Boletos",
        line=dict(color="brown", dash="dash")
    ))
    
    # Layout do gráfico
    fig.update_layout(
        title="Comparação do Tempo de Permanência: Contratos vs. Boletos",
        xaxis_title="Ano de Início",
        yaxis_title="Tempo de Permanência (anos)",
        showlegend=True,
        xaxis=dict(
            dtick=1,
            tickmode='linear'
        )
    )
    
    return fig

In [62]:
analisar_permanencia_comparada(tabela_nova_df)

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2040447384.py:24: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2040447384.py:25: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2040447384.py:28: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2040447384.py:29: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Contratos (analise de Sobrevivencia)

In [16]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from lifelines import KaplanMeierFitter

def analisar_sobrevivencia_kaplan_todos(tabela_filtrada):
    """
    Para cada ano de 2006 até 2024, calcula o tempo médio esperado de sobrevivência usando Kaplan-Meier,
    considerando dois cenários:
    1. Apenas contratos onde tipo_saida != "ATIVO".
    2. Todos os contratos.
    
    Retorna:
    - Gráfico comparando a evolução do tempo médio esperado ao longo dos anos para ambos os cenários.
    """
    
    # 🔹 Definir intervalo de anos
    ano_min = 2006
    ano_max = 2024
    
    resultados_filtrados = []
    resultados_todos = []
    
    for ano_filtro in range(ano_min, ano_max + 1):
        print(f"Calculando para contratos com data_inicio após {ano_filtro}...")
        
        # 🔹 Filtro 1: Apenas contratos que não são "ATIVO"
        df_filtrado = tabela_filtrada[(tabela_filtrada["data_inicio"].dt.year >= ano_filtro) &
                                      (tabela_filtrada["data_primeiro_boleto"].dt.year >= tabela_filtrada["data_inicio"].dt.year) &
                                      (tabela_filtrada["tipo_saida"] != "ATIVO")]
        
        # 🔹 Filtro 2: Todos os contratos
        df_todos = tabela_filtrada[(tabela_filtrada["data_inicio"].dt.year >= ano_filtro) &
                                   (tabela_filtrada["data_primeiro_boleto"].dt.year >= tabela_filtrada["data_inicio"].dt.year)]
        
        for df, resultados in [(df_filtrado, resultados_filtrados), (df_todos, resultados_todos)]:
            if df.empty:
                continue
            
            # 🔹 Converter colunas para tipos adequados
            df = df.copy()
            df["anos_contrato"] = df["anos_contrato"].astype(float)
            df["churn"] = df["churn"].apply(lambda x: 1 if x == 1 else 0).astype(int)
            
            # 🔹 Aplicar Kaplan-Meier
            kmf = KaplanMeierFitter()
            kmf.fit(df["anos_contrato"], event_observed=df["churn"])
            
            # 🔹 Calcular o tempo médio de vida esperado
            tempo_de_vida_esperado = np.trapz(kmf.survival_function_["KM_estimate"], kmf.survival_function_.index)
            
            resultados.append((ano_filtro, tempo_de_vida_esperado))
    
    # 🔹 Criar DataFrames de resultados
    df_resultados_filtrados = pd.DataFrame(resultados_filtrados, columns=["Ano", "Tempo de Vida Esperado"])
    df_resultados_todos = pd.DataFrame(resultados_todos, columns=["Ano", "Tempo de Vida Esperado"])
    
    # 🔹 Criar gráfico comparativo
    fig = go.Figure()
    
    fig.add_trace(go.Scatter(
        x=df_resultados_filtrados["Ano"].astype(str),
        y=df_resultados_filtrados["Tempo de Vida Esperado"],
        mode="lines+markers",
        name="Sem ATIVO",
        line=dict(color="red")
    ))
    
    fig.add_trace(go.Scatter(
        x=df_resultados_todos["Ano"].astype(str),
        y=df_resultados_todos["Tempo de Vida Esperado"],
        mode="lines+markers",
        name="Todos os Contratos",
        line=dict(color="blue")
    ))
    
    fig.update_layout(
        title="Evolução do Tempo de Vida Esperado ao Longo dos Anos",
        xaxis_title="Ano de Início",
        yaxis_title="Tempo de Vida Esperado (anos)",
        template="plotly_white",
        legend_title="Filtragem"
    )
    
    fig.show()

In [17]:
analisar_sobrevivencia_kaplan_todos(tabela_nova_df)

Calculando para contratos com data_inicio após 2006...
Calculando para contratos com data_inicio após 2007...
Calculando para contratos com data_inicio após 2008...
Calculando para contratos com data_inicio após 2009...
Calculando para contratos com data_inicio após 2010...
Calculando para contratos com data_inicio após 2011...
Calculando para contratos com data_inicio após 2012...
Calculando para contratos com data_inicio após 2013...
Calculando para contratos com data_inicio após 2014...
Calculando para contratos com data_inicio após 2015...
Calculando para contratos com data_inicio após 2016...
Calculando para contratos com data_inicio após 2017...
Calculando para contratos com data_inicio após 2018...
Calculando para contratos com data_inicio após 2019...
Calculando para contratos com data_inicio após 2020...
Calculando para contratos com data_inicio após 2021...
Calculando para contratos com data_inicio após 2022...
Calculando para contratos com data_inicio após 2023...
Calculando para contratos com data_inicio após 2024...

In [18]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from lifelines import WeibullFitter
from scipy.special import gamma

def analisar_sobrevivencia_weibull_todos(tabela_filtrada):
    """
    Para cada ano de 2006 até 2024, calcula o tempo médio esperado de sobrevivência usando Weibull,
    considerando dois cenários:
    1. Apenas contratos onde tipo_saida != "ATIVO".
    2. Todos os contratos.
    
    Retorna:
    - Gráfico comparando a evolução do tempo médio esperado ao longo dos anos para ambos os cenários.
    """
    
    # 🔹 Definir intervalo de anos
    ano_min = 2006
    ano_max = 2024
    
    resultados_filtrados = []
    resultados_todos = []
    
    for ano_filtro in range(ano_min, ano_max + 1):
        print(f"Calculando para contratos com data_inicio após {ano_filtro}...")
        
        # 🔹 Filtro 1: Apenas contratos que não são "ATIVO"
        df_filtrado = tabela_filtrada[(tabela_filtrada["data_inicio"].dt.year >= ano_filtro) &
                                      (tabela_filtrada["data_primeiro_boleto"].dt.year >= tabela_filtrada["data_inicio"].dt.year) &
                                      (tabela_filtrada["tipo_saida"] != "ATIVO")]
        
        # 🔹 Filtro 2: Todos os contratos
        df_todos = tabela_filtrada[(tabela_filtrada["data_inicio"].dt.year >= ano_filtro) &
                                   (tabela_filtrada["data_primeiro_boleto"].dt.year >= tabela_filtrada["data_inicio"].dt.year)]
        
        for df, resultados in [(df_filtrado, resultados_filtrados), (df_todos, resultados_todos)]:
            if df.empty:
                continue
            
            # 🔹 Converter colunas para tipos adequados
            df = df.copy()
            df["anos_contrato"] = df["anos_contrato"].astype(float)
            df["churn"] = df["churn"].apply(lambda x: 1 if x == 1 else 0).astype(int)
            
            # 🔹 Aplicar Weibull
            wf = WeibullFitter()
            wf.fit(df["anos_contrato"], event_observed=df["churn"])
            
            # 🔹 Estimar o tempo médio de vida esperado usando Weibull
            alpha, beta = wf.rho_, wf.lambda_
            tempo_de_vida_esperado = beta * gamma(1 + 1 / alpha)  # Esperança matemática de Weibull
            
            resultados.append((ano_filtro, tempo_de_vida_esperado))
    
    # 🔹 Criar DataFrames de resultados
    df_resultados_filtrados = pd.DataFrame(resultados_filtrados, columns=["Ano", "Tempo de Vida Esperado"])
    df_resultados_todos = pd.DataFrame(resultados_todos, columns=["Ano", "Tempo de Vida Esperado"])
    
    # 🔹 Criar gráfico comparativo
    fig = go.Figure()
    
    fig.add_trace(go.Scatter(
        x=df_resultados_filtrados["Ano"].astype(str),
        y=df_resultados_filtrados["Tempo de Vida Esperado"],
        mode="lines+markers",
        name="Sem ATIVO",
        line=dict(color="red")
    ))
    
    fig.add_trace(go.Scatter(
        x=df_resultados_todos["Ano"].astype(str),
        y=df_resultados_todos["Tempo de Vida Esperado"],
        mode="lines+markers",
        name="Todos os Contratos",
        line=dict(color="blue")
    ))
    
    fig.update_layout(
        title="Evolução do Tempo de Vida Esperado ao Longo dos Anos (Weibull)",
        xaxis_title="Ano de Início",
        yaxis_title="Tempo de Vida Esperado (anos)",
        template="plotly_white",
        legend_title="Filtragem"
    )
    
    fig.show()

In [19]:
analisar_sobrevivencia_weibull_todos(tabela_nova_df)

Calculando para contratos com data_inicio após 2006...
Calculando para contratos com data_inicio após 2007...
Calculando para contratos com data_inicio após 2008...
Calculando para contratos com data_inicio após 2009...
Calculando para contratos com data_inicio após 2010...
Calculando para contratos com data_inicio após 2011...
Calculando para contratos com data_inicio após 2012...
Calculando para contratos com data_inicio após 2013...
Calculando para contratos com data_inicio após 2014...
Calculando para contratos com data_inicio após 2015...
Calculando para contratos com data_inicio após 2016...
Calculando para contratos com data_inicio após 2017...
Calculando para contratos com data_inicio após 2018...
Calculando para contratos com data_inicio após 2019...
Calculando para contratos com data_inicio após 2020...
Calculando para contratos com data_inicio após 2021...
Calculando para contratos com data_inicio após 2022...
Calculando para contratos com data_inicio após 2023...
Calculando para contratos com data_inicio após 2024...

In [20]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from lifelines import CoxPHFitter

def analisar_sobrevivencia_cox_todos(df):
    """
    Para cada ano de 2006 até 2024, calcula o tempo médio esperado de sobrevivência usando o modelo de Cox,
    considerando dois cenários:
    1. Apenas contratos onde tipo_saida != "ATIVO".
    2. Todos os contratos.
    
    Retorna:
    - Gráfico comparando a evolução do tempo médio esperado ao longo dos anos para ambos os cenários.
    """
    
    # 🔹 Definir intervalo de anos
    ano_min = 2006
    ano_max = 2024

    resultados_filtrados = []
    resultados_todos = []
    
    df['data_inicio'] = pd.to_datetime(df['data_inicio'])
    df['data_primeiro_boleto'] = pd.to_datetime(df['data_primeiro_boleto'])

    for ano_filtro in range(ano_min, ano_max + 1):
        print(f"Calculando para contratos com data_inicio após {ano_filtro}...")

        # 🔹 Filtro 1: Apenas contratos que não são "ATIVO"
        df_filtrado = df[(df['data_inicio'].dt.year >= ano_filtro) & 
                         (df['data_primeiro_boleto'].dt.year >= df['data_inicio'].dt.year) & 
                         (df['tipo_saida'] != "ATIVO")].copy()

        # 🔹 Filtro 2: Todos os contratos
        df_todos = df[(df['data_inicio'].dt.year >= ano_filtro) & 
                      (df['data_primeiro_boleto'].dt.year >= df['data_inicio'].dt.year)].copy()

        # 🔹 Aplicar modelo de Cox
        for df_subset, resultados in [(df_filtrado, resultados_filtrados), (df_todos, resultados_todos)]:
            if df_subset.empty:
                continue

            # 🔹 Garantir que os dados estão corretos antes do modelo
            df_subset = df_subset[['anos_contrato', 'churn', 'total_valor_pago', 'boletos_gerados', 'ano_inicio']].copy()
            
            # 🔹 Remover NaN
            df_subset.dropna(inplace=True)

            # 🔹 Garantir que churn é binário (0 ou 1)
            df_subset['churn'] = df_subset['churn'].astype(int)

            # 🔹 Garantir que anos_contrato é positivo
            df_subset = df_subset[df_subset['anos_contrato'] > 0]

            if df_subset.empty:
                continue
            
            cph = CoxPHFitter()
            try:
                cph.fit(df_subset, duration_col="anos_contrato", event_col="churn")
                
                # 🔹 Estimar tempo médio de vida esperado
                tempo_de_vida_esperado = cph.predict_expectation(df_subset).mean()
                
                resultados.append((ano_filtro, tempo_de_vida_esperado))
            except Exception as e:
                print(f"⚠️ Erro ao ajustar o modelo para {ano_filtro}: {e}")

    # 🔹 Criar DataFrames de resultados
    df_resultados_filtrados = pd.DataFrame(resultados_filtrados, columns=["Ano", "Tempo de Vida Esperado"])
    df_resultados_todos = pd.DataFrame(resultados_todos, columns=["Ano", "Tempo de Vida Esperado"])

    # 🔹 Criar gráfico comparativo
    fig = go.Figure()
    
    # 🔹 Adicionar linha para contratos sem "ATIVO"
    fig.add_trace(go.Scatter(
        x=df_resultados_filtrados["Ano"].astype(str),
        y=df_resultados_filtrados["Tempo de Vida Esperado"],
        mode="lines+markers",
        name="Sem ATIVO",
        line=dict(color="red")
    ))
    
    # 🔹 Adicionar linha para todos os contratos
    fig.add_trace(go.Scatter(
        x=df_resultados_todos["Ano"].astype(str),
        y=df_resultados_todos["Tempo de Vida Esperado"],
        mode="lines+markers",
        name="Todos os Contratos",
        line=dict(color="blue")
    ))
    
    fig.update_layout(
        title="Evolução do Tempo de Vida Esperado ao Longo dos Anos (Cox)",
        xaxis_title="Ano de Início",
        yaxis_title="Tempo de Vida Esperado (anos)",
        template="plotly_white",
        legend_title="Filtragem"
    )
    
    fig.show()

In [21]:
analisar_sobrevivencia_cox_todos(tabela_nova_df)

Calculando para contratos com data_inicio após 2006...
Calculando para contratos com data_inicio após 2007...
Calculando para contratos com data_inicio após 2008...
Calculando para contratos com data_inicio após 2009...
Calculando para contratos com data_inicio após 2010...
Calculando para contratos com data_inicio após 2011...
Calculando para contratos com data_inicio após 2012...
Calculando para contratos com data_inicio após 2013...
Calculando para contratos com data_inicio após 2014...
Calculando para contratos com data_inicio após 2015...
Calculando para contratos com data_inicio após 2016...
Calculando para contratos com data_inicio após 2017...
Calculando para contratos com data_inicio após 2018...
Calculando para contratos com data_inicio após 2019...
Calculando para contratos com data_inicio após 2020...
Calculando para contratos com data_inicio após 2021...
Calculando para contratos com data_inicio após 2022...
Calculando para contratos com data_inicio após 2023...
Calculando para contratos com data_inicio após 2024...
⚠️ Erro ao ajustar o modelo para 2024: Convergence halted due to matrix inversion problems. Suspicion is high collinearity. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-modelMatrix is singular.

In [22]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from lifelines import KaplanMeierFitter, WeibullFitter, CoxPHFitter

def analisar_sobrevivencia_comparada(df):
    resultados = {"Ano": [], "Kaplan-Meier": [], "Weibull": [], "Cox": []}
    
    df["data_inicio"] = pd.to_datetime(df["data_inicio"])
    df["data_primeiro_boleto"] = pd.to_datetime(df["data_primeiro_boleto"])
    
    for ano_filtro in range(2006, 2025):
        print(f"Agora rodando para o ano {ano_filtro}...")
        
        df_filtrado = df[
            (df["data_inicio"].dt.year >= ano_filtro) &
            (df["data_primeiro_boleto"].dt.year >= df["data_inicio"].dt.year)
        ].copy()
        
        df_filtrado["anos_contrato"] = df_filtrado["anos_contrato"].astype(float)
        df_filtrado["churn"] = df_filtrado["churn"].astype(int)
        
        if df_filtrado.empty:
            continue
        
        resultados["Ano"].append(ano_filtro)
        
        # Kaplan-Meier
        kmf = KaplanMeierFitter()
        kmf.fit(df_filtrado["anos_contrato"], event_observed=df_filtrado["churn"])
        tempo_km = np.trapz(kmf.survival_function_["KM_estimate"], kmf.survival_function_.index)
        resultados["Kaplan-Meier"].append(tempo_km)
        
        # Weibull
        wf = WeibullFitter()
        wf.fit(df_filtrado["anos_contrato"], event_observed=df_filtrado["churn"])
        tempo_weibull = wf.lambda_ * np.math.gamma(1 + 1 / wf.rho_)
        resultados["Weibull"].append(tempo_weibull)
        
        # Cox
        colunas_cox = ["anos_contrato", "churn", "total_valor_pago", "boletos_gerados", "ano_inicio"]
        if all(col in df_filtrado.columns for col in colunas_cox):
            df_cox = df_filtrado[colunas_cox].dropna()
            if not df_cox.empty:
                cph = CoxPHFitter()
                cph.fit(df_cox, duration_col="anos_contrato", event_col="churn")
                tempo_cox = cph.predict_expectation(df_cox).mean()
                resultados["Cox"].append(tempo_cox)
            else:
                resultados["Cox"].append(None)
        else:
            resultados["Cox"].append(None)
    
    df_resultados = pd.DataFrame(resultados)
    
    # Plotando gráfico
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=df_resultados["Ano"].astype(str), y=df_resultados["Kaplan-Meier"],
                             mode="lines+markers", name="Kaplan-Meier", line=dict(color="blue")))
    fig.add_trace(go.Scatter(x=df_resultados["Ano"].astype(str), y=df_resultados["Weibull"],
                             mode="lines+markers", name="Weibull", line=dict(color="red")))
    fig.add_trace(go.Scatter(x=df_resultados["Ano"].astype(str), y=df_resultados["Cox"],
                             mode="lines+markers", name="Cox", line=dict(color="green")))
    fig.update_layout(
        title="Comparação do Tempo de Vida Esperado (Kaplan-Meier, Weibull, Cox)",
        xaxis_title="Ano de Início",
        yaxis_title="Tempo de Vida Esperado (anos)",
        template="plotly_white",
        legend_title="Modelos"
    )
    fig.show()
    
    return df_resultados

In [23]:
analisar_sobrevivencia_comparada(tabela_nova_df)

Agora rodando para o ano 2006...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2007...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2008...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2009...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2010...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2011...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2012...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2013...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2014...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2015...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2016...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2017...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2018...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2019...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2020...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2021...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2022...
Agora rodando para o ano 2023...
Agora rodando para o ano 2024...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\3672887850.py:37: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

     Ano  Kaplan-Meier   Weibull       Cox
0   2006      4.106550  4.185285  3.788145
1   2007      4.032235  4.125463  3.700631
2   2008      3.955941  4.062980  3.608783
3   2009      3.881762  4.001241  3.535839
4   2010      3.796218  3.928581  3.448305
5   2011      3.662615  3.813643  3.323534
6   2012      3.528967  3.696549  3.195741
7   2013      3.429518  3.636302  3.095553
8   2014      3.365504  3.615447  3.023689
9   2015      3.250233  3.554369  2.904372
10  2016      3.144958  3.493868  2.789897
11  2017      3.027022  3.420806  2.671439
12  2018      2.883061  3.337402  2.523027
13  2019      2.711323  3.234900  2.351134
14  2020      2.432548  2.923015  2.088357
15  2021      2.162536  2.734610  1.834673
16  2022      1.810580  2.312651  1.516164
17  2023      1.390588  1.818177  1.136716
18  2024      0.788234  1.086744  0.670455

### Boletos (analise de Sobrevivencia)

In [38]:
def analisar_sobrevivencia_kaplan_todos_boletos(tabela_filtrada):
    """
    Para cada ano de 2006 até 2024, calcula o tempo médio esperado de sobrevivência usando Kaplan-Meier,
    considerando dois cenários:
    1. Apenas contratos onde tipo_saida != "ATIVO".
    2. Todos os contratos.
    
    Retorna:
    - Gráfico comparando a evolução do tempo médio esperado ao longo dos anos para ambos os cenários.
    """
    
    # 🔹 Definir intervalo de anos
    ano_min = 2006
    ano_max = 2024
    
    resultados_filtrados = []
    resultados_todos = []
    
    for ano_filtro in range(ano_min, ano_max + 1):
        print(f"Calculando para contratos com data_inicio após {ano_filtro}...")
        
        # 🔹 Filtro 1: Apenas contratos que não são "ATIVO"
        df_filtrado = tabela_filtrada[(tabela_filtrada["data_primeiro_boleto"].dt.year >= ano_filtro) & 
                                      (tabela_filtrada["tipo_saida"] != "ATIVO")]
        
        # 🔹 Filtro 2: Todos os contratos
        df_todos = tabela_filtrada[(tabela_filtrada['data_primeiro_boleto'].dt.year >= ano_filtro)]
         
        for df, resultados in [(df_filtrado, resultados_filtrados), (df_todos, resultados_todos)]:
            if df.empty:
                continue
                
            # 🔹 Converter colunas para tipos adequados
            df = df.copy()
            df["boletos_gerados_anos"] = df["boletos_gerados_anos"].astype(float)
            df["churn"] = df["churn"].apply(lambda x: 1 if x == 1 else 0).astype(int)
                
            # 🔹 Aplicar Kaplan-Meier
            kmf = KaplanMeierFitter()
            kmf.fit(df["boletos_gerados_anos"], event_observed=df["churn"])
                
            # 🔹 Calcular o tempo médio de vida esperado
            tempo_de_vida_esperado = np.trapz(kmf.survival_function_["KM_estimate"], kmf.survival_function_.index)
                
            resultados.append((ano_filtro, tempo_de_vida_esperado))
    
    # 🔹 Criar DataFrames de resultados
    df_resultados_filtrados = pd.DataFrame(resultados_filtrados, columns=["Ano", "Tempo de Vida Esperado"])
    df_resultados_todos = pd.DataFrame(resultados_todos, columns=["Ano", "Tempo de Vida Esperado"])
    
    # 🔹 Criar gráfico comparativo
    fig = go.Figure()
    
    fig.add_trace(go.Scatter(
        x=df_resultados_filtrados["Ano"].astype(str),
        y=df_resultados_filtrados["Tempo de Vida Esperado"],
        mode="lines+markers",
        name="Sem ATIVO",
        line=dict(color="red")
    ))
    
    fig.add_trace(go.Scatter(
        x=df_resultados_todos["Ano"].astype(str),
        y=df_resultados_todos["Tempo de Vida Esperado"],
        mode="lines+markers",
        name="Todos os Contratos",
        line=dict(color="blue")
    ))
    
    fig.update_layout(
        title="Evolução do Tempo de Vida Esperado ao Longo dos Anos",
        xaxis_title="Ano de Início",
        yaxis_title="Tempo de Vida Esperado (anos)",
        template="plotly_white",
        legend_title="Filtragem"
    )
    
    fig.show()

In [39]:
analisar_sobrevivencia_kaplan_todos_boletos(tabela_nova_df)

Calculando para contratos com data_inicio após 2006...
Calculando para contratos com data_inicio após 2007...
Calculando para contratos com data_inicio após 2008...
Calculando para contratos com data_inicio após 2009...
Calculando para contratos com data_inicio após 2010...
Calculando para contratos com data_inicio após 2011...
Calculando para contratos com data_inicio após 2012...
Calculando para contratos com data_inicio após 2013...
Calculando para contratos com data_inicio após 2014...
Calculando para contratos com data_inicio após 2015...
Calculando para contratos com data_inicio após 2016...
Calculando para contratos com data_inicio após 2017...
Calculando para contratos com data_inicio após 2018...
Calculando para contratos com data_inicio após 2019...
Calculando para contratos com data_inicio após 2020...
Calculando para contratos com data_inicio após 2021...
Calculando para contratos com data_inicio após 2022...
Calculando para contratos com data_inicio após 2023...
Calculando para contratos com data_inicio após 2024...

In [42]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from lifelines import WeibullFitter
from scipy.special import gamma

def analisar_sobrevivencia_weibull_todos_boletos(tabela_filtrada):
    """
    Para cada ano de 2006 até 2024, calcula o tempo médio esperado de sobrevivência usando Weibull,
    considerando dois cenários:
    1. Apenas contratos onde tipo_saida != "ATIVO".
    2. Todos os contratos.
    
    Retorna:
    - Gráfico comparando a evolução do tempo médio esperado ao longo dos anos para ambos os cenários.
    """
    
    # 🔹 Definir intervalo de anos
    ano_min = 2006
    ano_max = 2024
    
    resultados_filtrados = []
    resultados_todos = []
    
    for ano_filtro in range(ano_min, ano_max + 1):
        print(f"Calculando para contratos com data_primeiro_boleto após {ano_filtro}...")
        
        df_filtrado = tabela_filtrada[(tabela_filtrada["data_primeiro_boleto"].dt.year >= ano_filtro) & 
                                      (tabela_filtrada["tipo_saida"] != "ATIVO")]
        
        # 🔹 Filtro 2: Todos os contratos
        df_todos = tabela_filtrada[(tabela_filtrada['data_primeiro_boleto'].dt.year >= ano_filtro)]
        
        for df, resultados in [(df_filtrado, resultados_filtrados), (df_todos, resultados_todos)]:
            if df.empty:
                continue
            
            # 🔹 Converter colunas para tipos adequados
            df = df.copy()
            df["boletos_gerados_anos"] = df["boletos_gerados_anos"].astype(float)
            df["churn"] = df["churn"].apply(lambda x: 1 if x == 1 else 0).astype(int)
            
            # 🔹 Aplicar Weibull
            wf = WeibullFitter()
            wf.fit(df["boletos_gerados_anos"], event_observed=df["churn"])
            
            # 🔹 Estimar o tempo médio de vida esperado usando Weibull
            alpha, beta = wf.rho_, wf.lambda_
            tempo_de_vida_esperado = beta * gamma(1 + 1 / alpha)  # Esperança matemática de Weibull
            
            resultados.append((ano_filtro, tempo_de_vida_esperado))
    
    # 🔹 Criar DataFrames de resultados
    df_resultados_filtrados = pd.DataFrame(resultados_filtrados, columns=["Ano", "Tempo de Vida Esperado"])
    df_resultados_todos = pd.DataFrame(resultados_todos, columns=["Ano", "Tempo de Vida Esperado"])
    
    # 🔹 Criar gráfico comparativo
    fig = go.Figure()
    
    fig.add_trace(go.Scatter(
        x=df_resultados_filtrados["Ano"].astype(str),
        y=df_resultados_filtrados["Tempo de Vida Esperado"],
        mode="lines+markers",
        name="Sem ATIVO",
        line=dict(color="red")
    ))
    
    fig.add_trace(go.Scatter(
        x=df_resultados_todos["Ano"].astype(str),
        y=df_resultados_todos["Tempo de Vida Esperado"],
        mode="lines+markers",
        name="Todos os Contratos",
        line=dict(color="blue")
    ))
    
    fig.update_layout(
        title="Evolução do Tempo de Vida Esperado ao Longo dos Anos (Weibull)",
        xaxis_title="Ano de Início",
        yaxis_title="Tempo de Vida Esperado (anos)",
        template="plotly_white",
        legend_title="Filtragem"
    )
    
    fig.show()

In [43]:
analisar_sobrevivencia_weibull_todos_boletos(tabela_nova_df)

Calculando para contratos com data_primeiro_boleto após 2006...
Calculando para contratos com data_primeiro_boleto após 2007...
Calculando para contratos com data_primeiro_boleto após 2008...
Calculando para contratos com data_primeiro_boleto após 2009...
Calculando para contratos com data_primeiro_boleto após 2010...
Calculando para contratos com data_primeiro_boleto após 2011...
Calculando para contratos com data_primeiro_boleto após 2012...
Calculando para contratos com data_primeiro_boleto após 2013...
Calculando para contratos com data_primeiro_boleto após 2014...
Calculando para contratos com data_primeiro_boleto após 2015...
Calculando para contratos com data_primeiro_boleto após 2016...
Calculando para contratos com data_primeiro_boleto após 2017...
Calculando para contratos com data_primeiro_boleto após 2018...
Calculando para contratos com data_primeiro_boleto após 2019...
Calculando para contratos com data_primeiro_boleto após 2020...
Calculando para contratos com data_primeiro_boleto após 2021...
Calculando para contratos com data_primeiro_boleto após 2022...
Calculando para contratos com data_primeiro_boleto após 2023...
Calculando para contratos com data_primeiro_boleto após 2024...

In [48]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from lifelines import KaplanMeierFitter, WeibullFitter, CoxPHFitter

def analisar_sobrevivencia_comparada_boletos(df):
    resultados = {"Ano": [], "Kaplan-Meier": [], "Weibull": [], "Cox": []}
    
    df["data_inicio"] = pd.to_datetime(df["data_inicio"])
    df["data_primeiro_boleto"] = pd.to_datetime(df["data_primeiro_boleto"])
    
    for ano_filtro in range(2006, 2025):
        print(f"Agora rodando para o ano {ano_filtro}...")
        
        
        df_filtrado = df[(df['data_primeiro_boleto'].dt.year >= ano_filtro)]
        
        df_filtrado["boletos_gerados_anos"] = df_filtrado["boletos_gerados_anos"].astype(float)
        df_filtrado["churn"] = df_filtrado["churn"].astype(int)
        
        if df_filtrado.empty:
            continue
        
        resultados["Ano"].append(ano_filtro)
        
        # Kaplan-Meier
        kmf = KaplanMeierFitter()
        kmf.fit(df_filtrado["boletos_gerados_anos"], event_observed=df_filtrado["churn"])
        tempo_km = np.trapz(kmf.survival_function_["KM_estimate"], kmf.survival_function_.index)
        resultados["Kaplan-Meier"].append(tempo_km)
        
        # Weibull
        wf = WeibullFitter()
        wf.fit(df_filtrado["boletos_gerados_anos"], event_observed=df_filtrado["churn"])
        tempo_weibull = wf.lambda_ * np.math.gamma(1 + 1 / wf.rho_)
        resultados["Weibull"].append(tempo_weibull)
        
        # Cox
        colunas_cox = ["boletos_gerados_anos", "churn", "total_valor_pago", "boletos_gerados", "ano_inicio"]
        if all(col in df_filtrado.columns for col in colunas_cox):
            df_cox = df_filtrado[colunas_cox].dropna()
            if not df_cox.empty:
                cph = CoxPHFitter()
                cph.fit(df_cox, duration_col="boletos_gerados_anos", event_col="churn")
                tempo_cox = cph.predict_expectation(df_cox).mean()
                resultados["Cox"].append(tempo_cox)
            else:
                resultados["Cox"].append(None)
        else:
            resultados["Cox"].append(None)
    
    df_resultados = pd.DataFrame(resultados)
    
    # Plotando gráfico
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=df_resultados["Ano"].astype(str), y=df_resultados["Kaplan-Meier"],
                             mode="lines+markers", name="Kaplan-Meier", line=dict(color="blue")))
    fig.add_trace(go.Scatter(x=df_resultados["Ano"].astype(str), y=df_resultados["Weibull"],
                             mode="lines+markers", name="Weibull", line=dict(color="red")))
    fig.add_trace(go.Scatter(x=df_resultados["Ano"].astype(str), y=df_resultados["Cox"],
                             mode="lines+markers", name="Cox", line=dict(color="green")))
    fig.update_layout(
        title="Comparação do Tempo de Vida Esperado (Kaplan-Meier, Weibull, Cox) Boletos",
        xaxis_title="Ano de Início",
        yaxis_title="Tempo de Vida Esperado (anos)",
        template="plotly_white",
        legend_title="Modelos"
    )
    fig.show()
    
    return df_resultados

In [47]:
analisar_sobrevivencia_comparada_boletos(tabela_nova_df)

Agora rodando para o ano 2006...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

Agora rodando para o ano 2007...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

Agora rodando para o ano 2008...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

Agora rodando para o ano 2009...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

Agora rodando para o ano 2010...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

Agora rodando para o ano 2011...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

Agora rodando para o ano 2012...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

Agora rodando para o ano 2013...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

Agora rodando para o ano 2014...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

Agora rodando para o ano 2015...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

Agora rodando para o ano 2016...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

Agora rodando para o ano 2017...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Agora rodando para o ano 2018...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

Agora rodando para o ano 2019...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2020...

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

Agora rodando para o ano 2021...

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

Agora rodando para o ano 2022...
Agora rodando para o ano 2023...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1614: ConvergenceWarning:

Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Agora rodando para o ano 2024...

C:\Users\gusta\AppData\Local\Temp\ipykernel_19432\2901084468.py:35: DeprecationWarning:

`np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\utils\__init__.py:1163: ConvergenceWarning:

Column boletos_gerados has high sample correlation with the duration column. This may harm convergence. This could be a form of 'complete separation'.     See https://stats.stackexchange.com/questions/11109/how-to-deal-with-perfect-separation-in-logistic-regression


c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\lifelines\fitters\coxph_fitter.py:1607: ConvergenceWarning:

Newton-Raphson convergence completed successfully but norm(delta) is still high, 3.780. This may imply non-unique solutions to the maximum likelihood. Perhaps there is collinearity or complete separation in the dataset?

     Ano  Kaplan-Meier   Weibull       Cox
0   2006      3.275181  3.313069  2.693612
1   2007      3.279460  3.337867  2.685934
2   2008      3.257811  3.326886  2.666621
3   2009      3.204174  3.278771  2.601608
4   2010      3.196053  3.275735  2.574420
5   2011      3.121430  3.214526  2.493044
6   2012      3.044760  3.155065  2.407888
7   2013      3.024959  3.153350  2.368391
8   2014      2.995450  3.158379  2.305534
9   2015      2.942267  3.148171  2.220363
10  2016      2.910302  3.179670  2.160316
11  2017      2.869057  3.233525  2.102718
12  2018      2.548126  2.820318  1.784977
13  2019      2.428750  2.759776  1.689892
14  2020      2.234421  2.561495  1.483679
15  2021      2.042788  2.421982  1.314195
16  2022      1.760537  2.164553  1.097443
17  2023      1.387422  1.870887  0.864019
18  2024      0.800091  1.031439  0.462475